"""empty message

Revision ID: 162edfd5dcfd
Revises: 
Create Date: 2021-08-29 14:42:26.966416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162edfd5dcfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
